### ISSUE TITLE
how to get calib file?

### ISSUE THREAD

**Issue by wolf943134497** [PerceptionRobotique/dualfisheye2equi#1]
Hi @GuicarMIS  Thanks for your great works!

Will the calib code be released? How to calib dual fisheye camera and imu?

**Comment by GuicarMIS** [comment]
Hi @wolf943134497,

The dualfisheye camera calib code is not yet about to be release. Lack of people working on it, unfortunately. It is mainly the released Hyscas (https://home.mis.u-picardie.fr/~g-caron/en/index.php?page=7#Hyscas), as the dualfisheye is considered a stereo rig of cameras following the model of Barreto, but with handling multi-planar calibration grid within another user interface. 

However, calibration files like https://github.com/PerceptionRobotique/dualfisheye2equi/blob/main/data/RicohThetaS_calib.xml can be filled in manually if you have another software that can do the calibration (or make a new one extending https://www.robots.ox.ac.uk/~cmei/Toolbox.html). 

Anyway, we did not work on the calibration of such camera with an IMU.

**Comment by wolf943134497** [comment]
@GuicarMIS   Thanks for your quick reply and suggestion.
